# Generated by Django 5.1 on 2024-08-27 23:17

import datetime
import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_student_level"),
        ("payments", "0003_delete_testclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[payments.models.validate_positive],
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="payment_complete",
            new_name="is_paid",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_code",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="TuitionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("orange_money", "Orange Money"),
                            ("mtn_money", "MTN Mobile Money"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
