# Generated by Django 5.1 on 2024-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="relation_ship",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Père", "Père"),
                    ("Mère", "Mère"),
                    ("Frère", "Frère"),
                    ("Sœur", "Sœur"),
                    ("Grand-mère", "Grand-mère"),
                    ("Grand-père", "Grand-père"),
                    ("Autre", "Autre"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("Licence", "Diplôme de Licence"),
                    ("Master", "Diplôme de Master"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Homme"), ("F", "Femme")],
                max_length=1,
                null=True,
            ),
        ),
    ]
