# Generated by Django 5.1 on 2024-09-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_parent_relation_ship_alter_student_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent",
            old_name="first_name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="parent",
            old_name="last_name",
            new_name="prénom",
        ),
    ]
